cupra_start_stop_charging:
  name: Cupra Start or Stop Charging
  description: Starts or stops charging of Cupra vehicles.
  fields:
    vin:
      name: VIN
      description: Vehicle identification number for the car.
      required: true
      example: VSSZZZ5FZMR001337
      selector:
        text:
    start_stop:
      name: Start or Stop
      description: Starts or stops charging.
      required: true
      selector:
        select:
          options:
            - "start"
            - "stop"

cupra_set_climatisation:
  name: Cupra Set Climatisation
  description: Sets climatisation in Cupra vehicles.
  fields:
    vin:
      name: VIN
      description: Vehicle identification number for the car.
      required: true
      example: VSSZZZ5FZMR001337
      selector:
        text:
    start_stop:
      name: Start or Stop
      description: Starts or stops climatisation.
      required: true
      selector:
        select:
          options:
            - "start"
            - "stop"
    target_temp:
      name: Target Temperature
      description: Sets target temperature in Celsius.
      required: false
      selector:
        number:
          min: 10
          max: 30
          unit_of_measurement: "ºC"

cupra_set_target_soc:
  name: Cupra Set Target SoC
  description: Sets the target SoC in Cupra vehicles.
  fields:
    vin:
      name: VIN
      description: Vehicle identification number for the car.
      required: true
      example: VSSZZZ5FZMR001337
      selector:
        text:
    target_soc:
      name: Target State of Charge
      description: Sets state of charge in percentage.
      required: true
      selector:
        number:
          min: 10
          max: 100
          step: 10
          unit_of_measurement: "%"

cupra_set_ac_charge_speed:
  name: Cupra Set AC Charge Speed
  description: Sets the AC charging speed in Cupra vehicles.
  fields:
    vin:
      name: VIN
      description: Vehicle identification number for the car.
      required: true
      example: VSSZZZ5FZMR001337
      selector:
        text:
    maximum_reduced:
      name: Maximum or Reduced
      description: Sets the AC charge speed.
      required: true
      selector:
        select:
          options:
            - "maximum"
            - "reduced"
