cupra_formentor_start_stop_charging:
  name: Iniciar/Detener Carga
  description: Inicia o detiene la carga del vehículo
  fields:
    vin:
      name: VIN
      description: VIN del vehículo
      required: true
    start_stop:
      name: Acción
      description: "start" para iniciar, "stop" para detener
      required: true

cupra_formentor_set_climatisation:
  name: Configurar Climatización
  description: Configura la climatización del vehículo
  fields:
    vin:
      name: VIN
      description: VIN del vehículo
      required: true
    start_stop:
      name: Acción
      description: "start" para iniciar, "stop" para detener
      required: true
    target_temp:
      name: Temperatura
      description: Temperatura objetivo en Celsius
      required: false

cupra_formentor_set_target_soc:
  name: Configurar SOC Objetivo
  description: Configura el nivel de carga objetivo
  fields:
    vin:
      name: VIN
      description: VIN del vehículo
      required: true
    target_soc:
      name: SOC
      description: Porcentaje de carga objetivo (10-100)
      required: true

cupra_formentor_set_ac_charge_speed:
  name: Configurar Velocidad de Carga AC
  description: Configura la velocidad de carga AC
  fields:
    vin:
      name: VIN
      description: VIN del vehículo
      required: true
    maximum_reduced:
      name: Velocidad
      description: "maximum" o "reduced"
      required: true